# Introdução ao NumPy

In [30]:
import numpy as np

## Arrays

In [45]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.ndim

1

In [48]:
print(a[1])
print(a[1:3])

2
[2 3]


## Array vs Listas

In [67]:
lista = [1,2,3,4]
print(lista * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [69]:
array = np.array([1,2,3,4])
print(array * 2)

[2 4 6 8]


In [72]:
# Cálculo de IMC
peso = np.array([67,81,120,90])
altura = np.array([1.68,1.70,1.75,1.85])
peso / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

## Matrizes

In [50]:
b = np.array([(1,2,3),(4,5,6)])

In [8]:
type(b)

numpy.ndarray

In [93]:
b.ndim

2

In [73]:
b.shape

(2, 3)

In [74]:
b.size

6

In [76]:
b.max()

6

In [77]:
b.min()

1

In [78]:
b.mean()

3.5

In [79]:
b.std()

1.707825127659933

In [80]:
b.sum()

21

In [56]:
print(b)
print(b[:,1])
print(b[0,:])

[[1 2 3]
 [4 5 6]]
[2 5]
[1 2 3]


In [39]:
print(np.dtype(b[1,1]))

int64


In [11]:
c = np.random.random((5,2))

In [34]:
c

array([[0.25930249, 0.03148999],
       [0.07989172, 0.03022459],
       [0.57539877, 0.27286237],
       [0.23780135, 0.78412124],
       [0.27748232, 0.05903038]])

In [37]:
c[1,1]

0.03022459069913841

In [38]:
print(np.dtype(c[1,1]))

float64


In [52]:
b2 = np.array([(1,2,3),(4,5,6)], np.float64)

In [53]:
print(b2)
print(np.dtype(b2[1,1]))

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [18]:
d = np.arange(10,50,5)

In [19]:
d

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
c.shape

(5, 2)

c.ndim

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.full((4,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [66]:
ar = np.random.randn(3,4)
print(ar)
arb = ar < 0
print(arb)

[[-0.62029206 -1.89003744  1.96988629 -0.17613239]
 [-0.82024793  0.98318404  2.36567609 -0.48307416]
 [-0.58306283  0.52677657 -1.25415702  1.11095268]]
[[ True  True False  True]
 [ True False False  True]
 [ True False  True False]]


## Operações com Matrizes

In [81]:
a = np.array([[1,2,3,4],[4,3,2,1]])
b = np.array([[1,2,3,4],[4,3,2,1]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6 8]
 [8 6 4 2]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [16  9  4  1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
a * 2

array([[2, 4, 6, 8],
       [8, 6, 4, 2]])

In [32]:
print(a)
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[1 2 3 4]
 [4 3 2 1]]
20
[5 5 5 5]
[10 10]


In [82]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [83]:
a.reshape(-1)

array([1, 2, 3, 4, 4, 3, 2, 1])

In [84]:
tree = np.random.random((5,3))

In [85]:
tree

array([[0.19878466, 0.85197701, 0.63891804],
       [0.989476  , 0.91048023, 0.4769858 ],
       [0.70298858, 0.81662286, 0.61363141],
       [0.24986852, 0.17178161, 0.19917692],
       [0.03997446, 0.60343388, 0.16429987]])

In [89]:
tree.reshape(3,5)

array([[0.19878466, 0.85197701, 0.63891804, 0.989476  , 0.91048023],
       [0.4769858 , 0.70298858, 0.81662286, 0.61363141, 0.24986852],
       [0.17178161, 0.19917692, 0.03997446, 0.60343388, 0.16429987]])

## Arquivos de Texto

In [90]:
np.savetxt("matriz1.txt",tree, delimiter=',')

In [91]:
dataset = np.loadtxt('matriz1.txt', delimiter=',')

In [92]:
dataset

array([[0.19878466, 0.85197701, 0.63891804],
       [0.989476  , 0.91048023, 0.4769858 ],
       [0.70298858, 0.81662286, 0.61363141],
       [0.24986852, 0.17178161, 0.19917692],
       [0.03997446, 0.60343388, 0.16429987]])